*&---------------------------------------------------------------------*
*& Include          YCL107_002_TOP
*&---------------------------------------------------------------------*

TABLES SCARR.
"화면의 INPUT필드에 값을 가져오기 위해 해당 테이블의 필드와 똑같은 이름의
" INPUT 필드 명이 일치하는 정보를 가져옴

DATA : OK_CODE TYPE SY-UCOMM,
       SAVE_OK TYPE SY-UCOMM.

DATA : GT_SCARR TYPE TABLE OF SCARR.


SELECTION-SCREEN BEGIN OF SCREEN 0101 AS SUBSCREEN. "SEL-SCR 인데 SUBSCREEN이다.
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(10) TEXT-L02 FOR FIELD S_CARRID. "항공사 ID
  SELECT-OPTIONS S_CARRID FOR SCARR-CARRID.
  SELECTION-SCREEN END OF LINE.


  SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) TEXT-L03 FOR FIELD S_CARRNM. "항공사 ID
  SELECT-OPTIONS S_CARRNM FOR SCARR-CARRNAME.
  SELECTION-SCREEN PUSHBUTTON 77(10) TEXT-L01 USER-COMMAND SEARCH.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK B01.
  SELECTION-SCREEN END OF SCREEN 0101.



"PUSHBUTTON 124(20)  시작위치 (버튼 사이즈,얼마나 긴 길이?)
